columns:
  - hr
  - map
  - rr
  - temp_c
  - spo2
  - creatinine
  - bilirubin
  - platelets
  - lactate
  - sofa_cardio
  - sofa_lab
  - anchor_age
  - gender
  - urine_output_6h_ml
  - label_12h


numerical_columns:
  - hr
  - map
  - rr
  - temp_c
  - spo2
  - creatinine
  - bilirubin
  - platelets
  - lactate
  - sofa_cardio
  - sofa_lab
  - anchor_age
  - urine_output_6h_ml


categorical_columns:
  - gender


target_column:
  - label_12h


drop_columns:
  - stay_id
  - hour
  - insurance
  - race
  - urine_output_ml
  - admission_type
