name: CI/CD Sepsis API on EC2

on:
  push:
    branches: [main]

jobs:
  Continuous-Integration:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          echo "Building image..."
          /usr/bin/docker build -t ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} .
          
          echo "Pushing image..."
          /usr/bin/docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}


  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted

    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Stop & Remove Old Container
        run: |
          docker stop sepsis-api || true
          docker rm sepsis-api || true

      - name: Run New Container on EC2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          
          docker run -d \
            --name sepsis-api \
            -p 5000:5000 \
            $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG